
pretrained_model_name_or_path: "stable-diffusion-v1-5/stable-diffusion-v1-5"
all_lora_dir: "lora_dir"
lora_dir: "anime"
generate_dir: "generate_dir"
apply_lora: True
prompt: 'a man with dark hair and brown eyes'
num_inference_steps: 30
num_img: 5
guidance_scale: 7.5
seed: 42